### ISSUE TITLE
Sign Up email confirmation configuration

### ISSUE THREAD

**Issue by jagonzalr** [proversity-org/edx-app-ios#1]
The sign up email confirmation sent when someone registers needs to get configured so it doesn't says "Your Platform Name Here"

<img width="867" alt="screen shot 2016-02-01 at 1 23 07 pm" src="https://cloud.githubusercontent.com/assets/3858265/12716113/0204e068-c8e7-11e5-8dae-4f21c69ec8c0.png">

**Comment by renevatium** [comment]
Can you check if this still happens please.
