### ISSUE TITLE
Deploy via AWS mobile hub

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-ios#34]
Deploy via AWS mobile hub

**Comment by jagonzalr** [comment]
@renevatium, looking at this, mobile hub only works for testing not deploy. Also reading more about it the only way to deploy iOS apps it's through OSX machines. AWS currently only supports Linux machines so even though we could do it through Jenkins (compatible with OSX) the machine that runs everything from testing, to building,  to deploying needs to be OSX. The thing of testing in mobile hub is that you need to send your IPA (which can only be done through an OSX machine) and then it will test it out on real devices (which is cool) but it automates nothing. Some alternatives are Circle CI (but costs a lot) or making our one local jenkins server in a Mac Mini. With that everytime we make changes to the code the Mac Mini works for us and makes everyone happy. An example: http://youandthegang.com/2015/continuous-integration-delivery-with-jenkins/

**Comment by renevatium** [comment]
Agreed. Thinking Circle deploy to Mobile Hub/Device Farm for testing and screens but lets see where Kea gets to with the Android/Jenkins deploy first.

**Comment by renevatium** [comment]
I'm going to leave this in backlog as a reminder.
