### ISSUE TITLE
Fix all colors for Proversity theme

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-ios#5]
All blue headers/text/buttons etc should be changed to the black/grey for Proversity theme.

**Comment by jagonzalr** [comment]
I'm consulting with Marli and she asks what is the black/grey theme. It's suppose to be grey/blue which Marli says the current one is correct.

**Comment by renevatium** [comment]
Assuming that's been confirmed with Carl/Krishan, awesome. Was going on the assumption that it needed to match current [connect](http://www.proversity.org/en/) theme, which has black buttons/dark text etc. No stress, we'll deal with this next week.
