### ISSUE TITLE
Investigate CircleCI iOS environment

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-ios#53]
Investigate the iOS deployment environment on CircleCI (verify cost to company)

**Comment by renevatium** [comment]
[Seed](https://circleci.com/gh/organizations/proversity-org/settings#osx-pricing) **$39/mo for lowest package:**
2x OS X concurrency
1-5 builds/day
500 max minutes/month +  .08/minute after that
Community support
1-2 team members

**Comment by renevatium** [comment]
Can also request special _Seed_ access for opensource projects by emailing billing@circleci.com

**Comment by 4eek** [comment]
@renevatium this looks like it's very worth it for us as it's such an important part of delivery. Happy to go ahead with the upgrade.

**Comment by renevatium** [comment]
@4eek awesome! Will open it up now and try the opensource route
