### ISSUE TITLE
segment mobile config

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-ios#6]
Investigate segment requirements and implement analytics tracking if possible.

**Comment by jagonzalr** [comment]
If we use segment then when submitting to the App Store then remember this:
"When you submit to the app store, be aware that Segment collects the IDFA for use in doing mobile install attribution with integrations like Mobile App Tracking. Even if you’re not currently doing mobile install attribution, if you get asked, “Does this app use the Advertising Identifier (IDFA)?” on this page, you’ll want to check the following three boxes:

“Attribute this app installation to a previously served advertisement”
“Attribute an action taken within this app to a previously served advertisement”
“I, YOUR_NAME, confirm that this app, and any third party…”
Note, you should not check the box labeled “Serve advertisements within the app” unless you are actually going to display ads."
